//-----------------------------------------------------------------------------------------
// uri (header only)
// Copyright (C) 2024 Fix8 Market Technologies Pty Ltd
//   by David L. Dight
// see https://github.com/fix8mt/uri
//
// Lightweight header-only C++20 URI parser
//
// Distributed under the Boost Software License, Version 1.0 August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//-----------------------------------------------------------------------------------------
#include <iostream>
#include <vector>
#include <stdexcept>
#include <string_view>
#include <getopt.h>
#include <fix8/uri.hpp>

//-----------------------------------------------------------------------------------------
using namespace FIX8;
using enum uri::component;

//-----------------------------------------------------------------------------------------
#include "uriexamples.hpp"

//-----------------------------------------------------------------------------------------
int main(int argc, char *argv[])
{
   static constexpr const char *optstr{"t:hlas"};
   static constexpr const std::array long_options
   {
      option{ "help",	no_argument,         nullptr, 'h' },
      option{ "list",	no_argument,         nullptr, 'l' },
      option{ "sizes",	no_argument,         nullptr, '2' },
      option{ "all",		no_argument,         nullptr, 'a' },
      option{ "test",	required_argument,   nullptr, 't' },
      option{}
   };

	for (int val; (val = getopt_long (argc, argv, optstr, long_options.data(), 0)) != -1; )
	{
		try
		{
			switch (val)
			{
			case ':': case '?':
				std::cout << '\n';
				[[fallthrough]];
			case 'h':
				std::cout << "Usage: " << argv[0] << " [-" << optstr << "]" << R"(
 -t [num] test to run
 -l list tests
 -s show sizes
 -a run all tests
 -h help)" << '\n';
				break;
			case 'l':
				for (int ii{}; ii < tests.size(); ++ii)
					std::cout << ii << '\t' << tests[ii].first << '\n';
				break;
			case 't':
				if (const auto tnum {std::stoul(optarg)}; tnum >= tests.size())
					throw std::range_error("invalid test case");
				else
					std::cout << uri{tests[tnum].first};
				break;
			case 's':
				std::cout << "uri: " << sizeof(uri) << "\nbasic_uri: " << sizeof(basic_uri) << '\n';
				break;
			case 'a':
				for (const auto& [src,vec] : tests)
					std::cout << uri{src} << '\n';
				std::cout << tests.size() << " test cases\n";
				break;
			default:
				break;
			}
		}
		catch (const std::exception& e)
		{
			std::cerr << "exception: " << e.what();
			if (optarg)
				std::cerr << " (" << static_cast<char>(val) << ':' << optarg << ')';
			std::cerr << std::endl;
			return 1;
		}
	}
	/*
   const uri u1{"https://www.example.com:8080/pages/from?country=au"};
   std::cout << u1 << '\n';
   std::cout << u1.get_component(uri::authority) << '\n';
   std::cout << u1.get_component(uri::host) << '\n';
	if (u1.test(uri::port))
		std::cout << u1.get_component(uri::port) << '\n';
   std::cout << u1.get_component(uri::query) << '\n';
	if (u1.test(uri::fragment))
		std::cout << u1.get_component(uri::fragment) << '\n';
	*/
   if (const basic_uri u1{ "ws://localhost:9229/f46db715-70df-43ad-a359-7f9949f39868" }; u1.count())
		std::cout << u1 << '\n';
	return 0;
}

